### ISSUE TITLE
【每日一题】- 2020-04-04 - core-js是什么？ 平时有用到过么？（直接或者间接）

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#109]

**Comment by Calvin-for-AI** [comment]
core-js是JavaScript标准库的polyfill,提供了对ES6以后甚至ES5(老版本)的api的兼容写法,例如promise,同时其替代api会识别低端浏览器例如ie8等并进行兼容.  平时不会直接用到(工具库函数一般用lodash),因为没有兼容低端浏览器的需求,但是肯定会间接用到,因为ts-loader要打包成es5代码而引用了babel,babel又引入core.js作全局变量替换
