### ISSUE TITLE
【每日一题】- 2020-04-08 - 讲一下单点登录的原理

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#111]

**Comment by maydaylike** [comment]
用户第一次访问应用的时候，因为还没有登录，会被引导着去认证系统登录，认证系统根据用户提供的登录信息进行身份校验，如果通过校验，认证系统将返回给用户一个认证的凭据：令牌。令牌作为用户访问其他地址的凭证，服务端接收到请求后首先通过认证系统校验令牌的合法性，如果校验成功，用户就可以在不用再次登录的情况下访问其他业务服务器。

**Comment by suukii** [comment]
### 同域单点登录

假设我们有 3 个顶级域名相同的系统：

- SSO 系统(用于登录) sso.suki.com
- A 系统 a.suki.com
- B 系统 b.suki.com

流程：

- 访问 A 系统时，发现没有登录，跳转到 SSO 系统完成登录，在 SSO 系统把 cookie 设置在顶域 suki.com，跳转回 A 系统
- 访问 B 系统时，携带 suki.com 中的 cookie，识别为已登录状态

同域单点登录利用的原理是，设置 cookie 时，不仅可以设置当前域名的 cookie，还可以设置顶级域名的 cookie

### 跨域单点登录

假设我们有 3 个部署在不同域名的系统：

- SSO 系统(用于登录) sso.com
- A 系统 a.com
- B 系统 b.com

流程：

- 访问 A 系统，发现没有登录，跳转到 SSO 系统完成登录并记住登录状态，在 SSO 系统生成令牌，带着令牌跳转回 A 系统
- A 系统拿到令牌后，通过服务端向 SSO 系统求证令牌的有效性，如果令牌有效，登录成功，在 a.com 写入 cookie
- 访问 B 系统，发现没有登录，跳转到 SSO 系统，发现 SSO 系统已经登录了，不需要重新登录，SSO 生成令牌并返回 B 系统
- B 系统拿到令牌后，通过服务端向 SSO 系统求证令牌的有效性，如果令牌有效，登录成功，在 b.com 写入 cookie

**Comment by zycFran** [comment]
> 访问 B 系统，发现没有登录，跳转到 SSO 系统，发现 SSO 系统已经登录了

这步是如何判断已经登录的呢？
