### ISSUE TITLE
【每日一题】- 2020-04-10 - MQ给你带了什么好处，设计初衷是什么？会带来什么缺点嘛？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#113]

**Comment by maydaylike** [comment]
好处：解耦、异步、削峰
初衷：同步处理技术，在性能、健壮性、可扩展性上都存在着诸多缺点使得异步处理模型在分布式应用上比起同步处理模型更具有吸引力。
缺点：可用性低、统复杂性高、数据一致性问题以及我不会
