### ISSUE TITLE
【每日一题】- 2020-04-24 - 写正则，限制小数最多两位 ，整数部分不超过五位数

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#118]
eg:
```
12345 // true
123456 // false
123.33 // true
12345.44 // true
22.4321 // false
...
```

**Comment by suukii** [comment]
* `/^0*\d{1,5}\.\d{1,2}$|^0*\d{1,5}$/`
* `/^0*\d{1,5}(\.\d{1,2})?$/`
* `/^0*\d{1,5}(?=(\.\d{1,2})?$)/`
* `/^0*\d{1,5}\.?((?<=\.)\d{1,2})?$/`

reg.test('12345.12')             // true
reg.test('123456.12')         // false
reg.test('123456.123')     // false
reg.test('00012345.12') // true
reg.test('000123456')  // false
reg.test('00012345')  // true
reg.test('00000.12') // true
reg.test('0.1')         // true
