### ISSUE TITLE
【每日一题】- 2020-05-05 - no-magic-string

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#122]
为什么eslint 有一个 rule 是 no-magic-number.   而没有类似的比如 no-magic-string？或者更广泛一点，为什么没有no-magic-literal?

**Comment by suukii** [comment]
### Why Constant Beats Magic Number

- 易读懂(前提是常量名起得好)；
- 代码易维护，修改时只需要改一个地方；
- 写注释文档也方便，只需要在定义常量的地方写一次；
- 更容易发现 typo，如果把常量名打错了编辑器会有提示，但如果不小心把 100 写成了 10 就有点难发现了；
- 如果想把某个数字改成参数的形式的话也很方便，只要定义一个和常量同名的形参就行；

### Why Magic String Might Be Bad

- 不是所有 string literal 都是 self-documented，所以很容易忘记它们的用途；
- 如果代码中多处用到相同的 string literal，修改的时候就要修改多个地方。当然，可以使用查找替换来完成，不过如果其中一处是内容相同用途不同的 string literal，这个修改就可能不是你想要的；
- typo 可能带来 bug；
```js
const move = dir => {
  if (dir === 'left') {
    // move left
  }
}
move('leftt') // passing 'leftt' instead of 'left'
```
- i18n unfriendly, 使用 string literal 的话，如果程序后续需要支持多语言，会相较麻烦一点；

Magic string can be evil too. 所以感觉是不是也应该有一个 no-magic-string rule 呢。

至于其他 literal，boolean, undefined, null 都只有一两个值就没必要了，object, array 之类的，也很少会有人这样子用吧。

**Comment by azl397985856** [comment]
https://lucifer.ren/blog/2020/05/05/why-no-magic-string/
