### ISSUE TITLE
【每日一题】- 2020-05-11 - 如何让下面的代码返回true？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#124]
```js
'我' === '菜鸡' // true
```

**Comment by chen00jian** [comment]
面试 结果 = true

**Comment by suukii** [comment]
### 方法1：借用隐式类型转换

做法：改写 `String` 原型上的 `valueOf` 方法让它始终返回 `菜狗`，然后把相等式的一边换成 `String` 对象；

原理：`==` 比较对象和基本类型的时候，会尝试把对象转换成基本类型(一般先尝试调用 `valueOf` 再尝试调用 `toString`)；

```js
String.prototype.valueOf = () => '菜狗';
new String('我') == '菜狗' // true
```

不过题目中是全等，这种解法似乎有点偏离题意。

### 方法2：tagged function

想到的第二种方法是障眼法哈哈。

原理：

1. 模板字符串可以用作函数调用；
2. 根据 ASI (自动添加分号) 机制，以下代码是会合并成一行执行的；

```js
(() => '菜狗')

`我` === '菜狗'
```

**Comment by azl397985856** [comment]
@suukii 是不是也可以借助编译的力量

**Comment by lxhguard** [comment]
你还在为自己不等于菜狗而发愁吗
```javascript
console.log=e=>!e;
console.log('我' === '菜狗')
```
