### ISSUE TITLE
【每日一题】- 2020-07-28 - Promise.all VS Promise. allSettled          Promise.any VS Promise.race

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#138]
Promise.all 和 Promise.allSettled  有什么区别？

 Promise.any 和 Promise.race  有什么区别？

**Comment by azl397985856** [comment]
要区别这几个 API，我们首先需要理解一个词 **settled**。 settled 指的是 resolved 或者 rejected 都可以，只要不是 pending 即可。

有了这个只是就简单了。

- Promise.all 和  Promise.allSettled 的区别在于 all 需要全部 resolve 才继续执行 then，而 allSettled 则是需要全部 settled 才去继续执行 then。 因此 **all 会短路，而 allSettled 则不会**。
- Promise.any 和  Promise.race 的区别在于 any 需要有一个 resolve 才继续执行 then，而 race 则是需要有一个 settled 才去继续执行 then。 由于两者都只需要一个满足条件即可，因此 **any 和 race 都会短路**。

**Comment by suukii** [comment]
## Promise.all VS Promise.allSettled

- Promise.all: 参数中的 Promise 全部 resolve 了，Promise.all 才会 resolve，如果有一个 reject 了，Promise.all 就会马上 reject。
- Promise.allSettled: 等到全部 Promise 都是 settled 状态时，无论 resolved 或者 reject，Promise.allSettled 就会 resolve，而且它永远都不会 reject。

## Promise.any VS Promise.race

- Promise.any: 只要有一个 resolve 了就会 resolve，或者等到全部都 reject 的时候 any 就会 reject。
- Promise.race: 只要有一个 settled 了 race 就会 resolve 或者 reject，取决于 settled 的具体状态。
