### ISSUE TITLE
【每日一题】- 2019-08-15 - 控制console

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#15]
我们在合作开发的过程中，经常碰到别人在代码中加入console.log的调试代码，
这个时候你在开发你的部分的时候就有可能由于引入他的组件，导致控制台出现很多你
并不关心的信息，干扰你的调试。

一种方式是禁止提交console的代码，那如果不可以禁止，我们怎么才能不看到别人的console输出，
而只看到自己的console呢？

**Comment by TiaossuP** [comment]
1. console.log 只应该在开发时存在，提交到远端代码库的代码不应该有 console.log 了
2. console 当然也是有 filter 的。所以也可以先随便封装一个自己的 log 函数（用 snippet 也一样），然后在 console 的 Filter 输入框里填一个 myLog
```javascript
function myLog(...args) {
  console.log('myLog', ...args);
}
```

**Comment by xiaofuuu** [comment]
打断点点方式最方便
