### ISSUE TITLE
【每日一题】- 2020-09-15 - 响应头 content-type  的奇幻之旅

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#150]
浏览器拿到一个资源后， 会首先去读取 response header 的 content-type，根据不同的值，采取不同的策略。 

- 如果是图片就图片处理器处理
- 如果是JS 就给 JS 引擎处理
- 。。。

那么，如果：

- 服务端没有返回 content-type 呢？
- 服务端返回错误的 content-type 呢？

**Comment by suukii** [comment]
MIME Sniffing，就是浏览器会通过读取一部分响应内容来确定 MIME Type。

[MIME Sniff Spec](https://mimesniff.spec.whatwg.org/)
