### ISSUE TITLE
【每日一题】- 2020-10-09 - 以下 shell 的作用是什么？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#151]
```bash
mkfifo pipe1
mkfifo pipe2
echo -n run | cat - pipe1 > pipe2 &
cat <pipe2 > pipe1
```

**Comment by suukii** [comment]
```shell
mkfifo pipe1
```

- 创建了一个 FIFO(named pipe) pipe1(可以把它看成一个文件)
  
```shell
mkfifo pipe2
```

- 创建了一个 FIFO(named pipe) pipe2

```shell
echo -n run | cat - pipe1 > pipe2 &
```

- `echo run` 输入字符串 `run`，`-n` 参数去除 trailing line
- `|` pipe to
- `cat - pipe1 > pipe2` 将输入(`run`) 和 pipe1(暂时没有内容) 的内容输入到 pipe2
- `&` run in background

```shell
cat < pipe2 > pipe1
```

- 将 pipe2 的内容作为 `cat` 命令的输入，然后再输出到 pipe1 中。

一顿操作之后，pipe1 和 pipe2 中的内容都是 `run`。

> 通过 google 之后猜的 ╮(╯▽╰)╭

**Comment by feikerwu** [comment]
新建两个命名管道pipe1, pipe2, 将两个管道两端接合，形成一个环，字符串在两个管道间不断拷贝。整挺好，就是死循环废机器。
