### ISSUE TITLE
【每日一题】- 2021-07-12 数组的索引为什么从 0 开始?而不是从 1 开始？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#158]

**Comment by Talent-Rain** [comment]
- 对于 JS 而言，数组变量其实就是一个指针，而数组的索引值表示偏移量的个数；
- 好像设计数组的时候，每个值的类型都是一样的，所以每一个存缓存的内存也是一样的，一个值所占的内存大小就是一个偏移量的大小；
- 所以对于数组的第一个值，就是指针所在的位置，偏移量为0；对于第二个值，就是偏移了第一个值的位置，所以是 start + 1 * 偏移量；
- 这样当我们用索引来求数组索引值为 N 的值的时候，给的是 arr[n] , 计算机到 start+n*K 就能找到所在位置了;如果以 1 开始，那么每次查找就要多处理一次 n-1 的操作 start+(n-1)*K
- 以上是一个小前端看了之前的书了解的，谢谢

**Comment by azl397985856** [comment]
1. 索引的含义是偏移量（offset），偏移量从 0 开始，因此索引也从 0 开始。
2. 数组需要支持随机访问，一种实现方式就是通过 **基值+偏移量*每项的字节数** 访问任意索引位置。如果索引从 1 开始，那么偏移量就等于索引-1，这样会多一次减法运算。
