### ISSUE TITLE
【每日一题】- 2019-08-05 - 数据格式转化问题

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#2]
已知数据格式：

const userToSkill = {
  robert: ["programming", "design", "reactjs"],
  kimia: ["java", "backend", "services"],
  patrick: ["reactjs"],
  chris: ["reactjs", "programming"]
};

转化成

const skillToUser = {
  programming: ["robert", "chris"],
  reactjs: ["patrick", "robert", "chris"],
  java: ["kimia"],
  backend: ["kimia"],
  services: ["kimia"],
  design: ["robert"]
};

扩展： 

完成函数：

function setOfUsersWithSimillarSkills(userToSkill) {
  
}

期望输出：  ["robert", "chris"]

**Comment by woohs** [comment]
1.
```javascript
function demo(userToSkill) {
    let obj = {}
    for(let item in userToSkill) {
        userToSkill[item].forEach(i => {
            if(obj[i]) {
                obj[i].push(item)
            }else {
                obj[i] = [item]
            }
        })
    }
	return obj
}
```

**Comment by azl397985856** [comment]
> ```js
> function demo(userToSkill) {
>     let obj = {}
>     for(let item in userToSkill) {
>         userToSkill[item].forEach(i => {
>             if(obj[i]) {
>                 obj[i].push(item)
>             }else {
>                 obj[i] = [item]
>             }
>         })
>     }
> 	return obj
> }
> ```
1. 注意命名
2. 虽然技能不大可能出现falsy的值。但是最好还是可以严谨一点

**Comment by hjx5309** [comment]
function setOfUsersWithSimillarSkills(userToSkill) {
   var skillToUser ={};
   var keylist = Object.entries(userToSkill);
   
   keylist.map(item=>{
     let [key,value] = item;
     value.map(obj=>{
      skillToUser[obj]?skillToUser[obj].push(key):skillToUser[obj]=[key]
     })
   })
   return skillToUser
}

**Comment by hjx5309** [comment]
```js
function setOfUsersWithSimillarSkills(userToSkill) {
   const skillToUser ={};
   const keylist = Object.entries(userToSkill);
   
   keylist.foreach(item=>{
     let [key,value] = item;
     value.foreach(obj=>{
      skillToUser[obj]?skillToUser[obj].push(key):skillToUser[obj]=[key]
     })
   })
   return skillToUser
}
```

**Comment by HEternally** [comment]
```js
function setUserToSkill(userToSkill){
	let skillToUser = {};
	for (let [key,value] of Object.entries(userToSkill)) {
		value.forEach(skill=>{
			skill in skillToUser ?  skillToUser[skill].push(key) : skillToUser[skill] = Array.of(key);
        });
    }
  return skillToUser;
}
```

**Comment by azl397985856** [comment]
> ```js
> function setUserToSkill(userToSkill){
> 	let skillToUser = {};
> 	for (let [key,value] of Object.entries(userToSkill)) {
> 		value.forEach(skill=>{
> 			skill in skillToUser ?  skillToUser[skill].push(key) : skillToUser[skill] = Array.of(key);
>         });
>     }
>   return skillToUser;
> }
> ```

里面的let都是没有必要的。

**Comment by azl397985856** [comment]
> ```
> function setOfUsersWithSimillarSkills(userToSkill) {
>    var skillToUser ={};
>    var keylist = Object.entries(userToSkill);
>    
>    keylist.map(item=>{
>      let [key,value] = item;
>      value.map(obj=>{
>       skillToUser[obj]?skillToUser[obj].push(key):skillToUser[obj]=[key]
>      })
>    })
>    return skillToUser
> }
> ```
1. 注意格式化
2. 尽量使用const，而不是var， 
3. 这里的map是没有必要的

**Comment by Tcdian** [comment]
```javascript
function setOfUsersWithSimillarSkills(userToSkill) {
    const userToSkillEntries = Object.entries(userToSkill);
    return userToSkillEntries.reduce((prevSkillToUser, [user, skills]) => {
        skills.forEach((skill) => {
            if (prevSkillToUser.hasOwnProperty(skill)) {
                prevSkillToUser[skill].push(user);
            } else {
                prevSkillToUser[skill] = [user];
            }
        });
        return prevSkillToUser;
    }, {});
}
```

**Comment by azl397985856** [comment]
参考答案：

```js
function transform(userToSkill) {
  const skillToUser = {};
  for (const k in userToSkill) {
    userToSkill[k].forEach(skill => {
      if (skillToUser[skill] === void 0) {
        skillToUser[skill] = [k];
      } else {
        skillToUser[skill].push(k);
      }
    });
  }

  return skillToUser;
}
```


扩展：

```js
function backtrack(list, tempList, nums, start) {
  list.push(intersect(...tempList));
  for(let i = start; i < nums.length; i++) {
      tempList.push(nums[i]);
      backtrack(list, tempList, nums, i + 1);
      tempList.pop();
  }
}
/**
* @param {number[]} nums
* @return {number[][]}
*/
function subsets(nums) {
  const list = [];
  backtrack(list, [], nums, 0);
  return list;
};

function intersect(arr1, ...rest) { 
  const set = new Set();
  if (rest.length === 0) return set;
  const s1 = new Set(arr1);
  const restSet = rest.map(a => new Set(a));
  for (const x of s1) {
    if (restSet.every(s => s.has(x))) {
      set.add(x);
    }
  }
  return set;
}
function maxByLength(list) {
  let max = 0;
  let maxIndex = 0;

  for(let i = 0; i < list.length; i++) {
    if (list.length > max) {
      max = list.length;
      maxIndex = i;
    }
  }
  return list[maxIndex];
}

function setOfUsersWithSimillarSkills(userToSkill) {
  const mapper = transform(userToSkill);
  const sets = subsets(Object.values(mapper).filter(q => q.length > 1));
  const list = sets.map(set => Array.from(set)).filter(q => q.length);
  return maxByLength(list)
}
```

**Comment by MujunZ** [comment]
```js
const transform = userToSkill => 
  Object.entries(userToSkill).reduce((skillToUser, [user, skills]) => 
    skills.reduce((skillToUser, skill) =>({
      ...skillToUser,
      [skill]: skillToUser[skill] ? skillToUser[skill].concat(user) : [skill]
    }), skillToUser), {})
```

**Comment by MujunZ** [comment]
@azl397985856  backtrack 那个没看懂。能不能讲一讲？

**Comment by azl397985856** [comment]
> @azl397985856 backtrack 那个没看懂。能不能讲一讲？

仓库里面很多这种回溯法解题的，你可以参考一下。  比如  subsets问题

**Comment by azl397985856** [comment]
closed by https://github.com/azl397985856/fe-interview/pull/6

**Comment by DevilRoshan** [comment]
> 参考答案：
> 
> ```js
> function transform(userToSkill) {
>   const skillToUser = {};
>   for (const k in userToSkill) {
>     userToSkill[k].forEach(skill => {
>       if (skillToUser[skill] === void 0) {
>         skillToUser[skill] = [k];
>       } else {
>         skillToUser[skill].push(k);
>       }
>     });
>   }
> 
>   return skillToUser;
> }
> ```
> 
> 扩展：
> 
> ```js
> function backtrack(list, tempList, nums, start) {
>   list.push(intersect(...tempList));
>   for(let i = start; i < nums.length; i++) {
>       tempList.push(nums[i]);
>       backtrack(list, tempList, nums, i + 1);
>       tempList.pop();
>   }
> }
> /**
> * @param {number[]} nums
> * @return {number[][]}
> */
> function subsets(nums) {
>   const list = [];
>   backtrack(list, [], nums, 0);
>   return list;
> };
> 
> function intersect(arr1, ...rest) { 
>   const set = new Set();
>   if (rest.length === 0) return set;
>   const s1 = new Set(arr1);
>   const restSet = rest.map(a => new Set(a));
>   for (const x of s1) {
>     if (restSet.every(s => s.has(x))) {
>       set.add(x);
>     }
>   }
>   return set;
> }
> function maxByLength(list) {
>   let max = 0;
>   let maxIndex = 0;
> 
>   for(let i = 0; i < list.length; i++) {
>     if (list.length > max) {
>       max = list.length;
>       maxIndex = i;
>     }
>   }
>   return list[maxIndex];
> }
> 
> function setOfUsersWithSimillarSkills(userToSkill) {
>   const mapper = transform(userToSkill);
>   const sets = subsets(Object.values(mapper).filter(q => q.length > 1));
>   const list = sets.map(set => Array.from(set)).filter(q => q.length);
>   return maxByLength(list)
> }
> ```

```
function maxByLength(list) {
  let max = 0;
  let maxIndex = 0;

  for(let i = 0; i < list.length; i++) {
    if (list[i].length > max) {
      max = list[i].length;
      maxIndex = i;
    }
  }
  return list[maxIndex];
}
```
