### ISSUE TITLE
【每日一题】- 2019-08-28 - 实现Array.prototype.find

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#24]
功能： 返回数组中满足提供的测试函数的第一个元素的值。否则返回 undefined。

语法： arr.find(callback[, thisArg])

callback是在数组每一项上执行的函数，接收 3 个参数：
- element 当前遍历到的元素。
- index可选 当前遍历到的索引。
- array可选 数组本身。

thisArg可选 执行回调时用作this 的对象。

eg:

```js
var array1 = [5, 12, 8, 130, 44];

var found = array1.find(function(element) {
  return element > 10;
});

console.log(found);
// expected output: 12
```

更多关于find的介绍请参考： https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by yjua** [comment]
```javascript
Array.prototype.finds = function(callback,thisArg){
    if(typeof callback !== 'function') {
        throw new TypeError('callback should be a function'); 
    }
    var obj = Object(this);
    var len = obj.length, k = 0;
    while(k < len){
        if(callback.call(thisArg,obj[k],k,obj)){
            return obj[k];
        }
        k++
    }
    return undefined;
}
```

**Comment by azl397985856** [comment]
> ```js
> Array.prototype.finds = function(callback,thisArg){
>     if(typeof callback !== 'function') {
>         throw new TypeError('callback should be a function'); 
>     }
>     var obj = Object(this);
>     var len = obj.length, k = 0;
>     while(k < len){
>         if(callback.call(thisArg,obj[k],k,obj)){
>             return obj[k];
>         }
>         k++
>     }
>     return undefined;
> }
> ```

有没有想去领一下
