### ISSUE TITLE
【每日一题】– 2019-09-29 - 判断一个字符串是否是纯中文组成

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#37]
eg:

1. '中国' // true

2. '中国ren' // false

3. 'ren' // false

**Comment by HEternally** [comment]
![image](https://user-images.githubusercontent.com/26925078/65825124-a52a3a00-e2a5-11e9-8606-0943aeb40545.png)

**Comment by azl397985856** [comment]
如果是空字符串呢

**Comment by azl397985856** [comment]
```js
function isChineseWord(word) {
  return /^[\u4e00-\u9fa5]+$/.test(word);
}
```
