### ISSUE TITLE
【每日一题】– 2019-10-09 - 以下说法正确的是？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#39]
1. 通过new URL('www.taobao.com') ，可以解析url内容。
2. console.log()是异步调用
3. Async functions本质上是Generators的语法糖
4. 在发布NPM模块时，版本号可以任意
5. process.nextTrick()和setImmediate()执行时机一致
6. Node.js是一门后端语言

**Comment by bin-git** [comment]
不会啊，请大神详解。多谢

**Comment by azl397985856** [comment]
> 不会啊，请大神详解。多谢

哪个不会啊

**Comment by bin-git** [comment]
有参考答案不？




------------------ 原始邮件 ------------------
发件人: "lucifer"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 中午12:29
收件人: "azl397985856/fe-interview"<fe-interview@noreply.github.com>;
抄送: "爱折网【azhew.com】"<554115339@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [azl397985856/fe-interview] 【每日一题】– 2019-10-09 - 以下说法正确的是？ (#39)



 
不会啊，请大神详解。多谢
  
哪个不会啊

**Comment by azl397985856** [comment]
1.  new URL(url, [base])第一个参数必须为一个完整url（不能缺少协议）或相对url。
2. 正确
3.  async function本质上是generators+ promises模式的语法糖
4.  NPM模块版本号必须为x.y.z形式。 即semver
5. process.nextTrick是微任务，setImmediate是宏任务，执行时机不一致
6. nodejs是js运行时，不是语言，也不是js引擎

**Comment by bin-git** [comment]
“nodejs是js运行时”
这句话是不是少了什么东西啊？咋个看着别扭

**Comment by azl397985856** [comment]
> “nodejs是js运行时”
> 这句话是不是少了什么东西啊？咋个看着别扭

运行时就是runtime
