### ISSUE TITLE
【每日一题】– 2019-10-10 - 下列对css外边距描述正确的是（不考虑BFC对边距的影响

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#40]
1. 外边距的css代码是padding
2. 两个上下相邻的同级元素Div1，Div2。Div1的下边距是10px，Div2的上边距是10px。Div1和Div2的间距是20px
3. 两个上下相邻的同级元素Div1，Div2。Div1的下边距是20px，Div2的上边距是10px。Div1和Div2的间距是20px
4. 外边距的值为（10px 20px 30px）。所以其上边距为10px，下边距为20px，左边距为30px，右边距为30px
5. 一个空元素的高度，边框，内边距都是0，上下外边距为20px，那么这个空元素的框模型的高度为40px
6. 一个空元素的高度，边框，内边距都是0，上下外边距为20px，那么这个空元素的框模型的高度为20px

**Comment by bin-git** [comment]
2错，应该是10px，垂直边距合并
4错，上10px，左右20px，下30px
5，6，不会

**Comment by bin-git** [comment]
答案还没有更新呢？

**Comment by azl397985856** [comment]
块级元素的上外边距和下外边距有时会合并（或折叠）为一个外边距，其大小取其中的最大者，这种行为称为外边距折叠（margin collapsing），有时也翻译为外边距合并，通常情况下上下两个相邻块元素的margin会发生合并。
一个空元素中不包含任何内容，并且在其 margin-top 与 margin-bottom 之间没有边框、内边距、行内内容、height、min-height 将两者分开，也会发生折叠。

**Comment by weisaimeigithub** [comment]
实践一下就会发现了
