### ISSUE TITLE
【每日一题】– 2019-10-11 - 对于解构以下说法错误的是

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#41]
1. 不完全解构，也会成功，不会报错。
2. 只要支持Iterator接口，都可以被解构赋值。
3. null可以替代默认值，而成功的解构赋值。
4. 结构中不定参数可以出现在除第一个以外的其它的其他位置。
5. 解构是先找到同名的属性，然后再赋给对应的变量。
6. 默认值可以引用解构赋值的其他变量，但该变量必须已经声明。

**Comment by HEternally** [comment]
3、默认值要严格等于undefined才会生效；
4、不定参数应该是只能在最后的位置
