### ISSUE TITLE
【每日一题】– 2019-10-21 - 某主机的IP地址为202.117.131.12/20，其子网掩码是多少

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#44]
头条面试题

**Comment by HEternally** [comment]
'/'后面的数字表示子网掩码的位数；
202.117.131.12/20代表前20位代表网络号，后12位代表主机号；
前20位全1，后12位全零的IP地址为255.255.240.0（子网掩码）
把主机号全换成1就是202.117.137.12/20的最多主机数ip地址，范围为：202.117.137.12-202.117.207.255

**Comment by azl397985856** [comment]
关于子网掩码的介绍可以看这里 https://lucifer.ren/fe-interview/#/./topics/network/net-mask
