### ISSUE TITLE
【每日一题】– 2019-10-23 - 如何实现一个检测网站技术栈的功能？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#46]
市面上有一个插件和工具可以检测网站的技术栈，比如前端用的什么框架，什么工具库，后端用的什么服务等。那么他们的原理是什么？

**Comment by FontEndArt** [comment]
统计出来各种各样工具库暴露在全局的变量名  然后加上利用AST分析网页源码的关键词
比如React、Vue等   然后就是elementui和antd这种的组件库 iconfont 通过分析网页中的class即可得到
汇总去重后差不多就是该网站用到的框架、工具库、组件库等

至于使用了什么服务，不太懂，可以考虑通过代理XML对象分析来确定，一般来说如果使用了nginx或者express这种的  大部分都会在报文中提现出来

**Comment by azl397985856** [comment]
参考： https://github.com/AliasIO/Wappalyzer

也可以参考我每日一荐项目中2019-10-24[技能]： https://github.com/azl397985856/daily-featured
