### ISSUE TITLE
【每日一题】- 2019-11-06 - 删除文件是否需要对该文件具有写权限，为什么？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#52]

**Comment by feikerwu** [comment]
不需要文件的写权限，需要文件所在目录的写和执行权限，删除文件相当于更改目录内容，所以需要目录有写权限，进入到目录执行了进入目录这样一个操作，需要执行权限

**Comment by feikerwu** [comment]
认领

**Comment by azl397985856** [comment]
@feikerwu done

**Comment by azl397985856** [comment]
已合并 https://github.com/azl397985856/fe-interview/blob/master/docs/daily/2019-11-14.md
