### ISSUE TITLE
【每日一题】- 2019-12-02 - 在Vue中， 什么时候data可以是对象，而不是函数？为什么？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#75]

**Comment by BrucePhoebus** [comment]
data是一个对象的时候就是当前vue对象的数据对象，私有使用，一般在new Vue实例的时候是使用对象，运行自己以及子组件访问组件时是一个函数是为了将数据暴露到全局，允许外部组件交互

**Comment by azl397985856** [comment]
正如[Vue 官方文档](https://cn.vuejs.org/v2/guide/components.html#data-%E5%BF%85%E9%A1%BB%E6%98%AF%E4%B8%80%E4%B8%AA%E5%87%BD%E6%95%B0)描述的那样，如果是组件，那么data必须是一个函数。 原因在于组件的实例可能会有多个。为了避免互相干扰，需要用户使用函数，每个组件实例都返回一个全新的对象，从而避免相互之间的影响。 

但是如果你是顶层的app，由于同一个应用理论上只应该有一个。因此我们可以将其设置成对象，也不存在上述的问题。
