### ISSUE TITLE
【每日一题】- 2019-12-03 - 用户行为对浏览器缓存的影响

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#76]
以下各种情景，缓存是如何起作用的？

1. 打开网页，地址栏输入地址
2. 普通刷新 (F5)
3. 强制刷新 (Ctrl + F5)

**Comment by coldcodebeer** [comment]
- 打开网页，地址栏输入地址: 强缓存->弱缓存
- 当 F5 刷新网页时，跳过强缓存，但是会检查协商缓存；
- 当 Ctrl + F5 强制刷新页面时，直接从服务器加载，跳过强缓存和协商缓存
