### ISSUE TITLE
【每日一题】- 什么是事件循环？调用堆栈和任务队列之间有什么区别？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#79]

**Comment by kevlin-sean** [comment]
![img](https://user-gold-cdn.xitu.io/2018/6/4/163c83c3e5f0ccca?imageView2/0/w/1280/h/960/format/webp/ignore-error/1)

![img](https://user-gold-cdn.xitu.io/2018/5/16/163677dda920b2af?imageView2/0/w/1280/h/960/format/webp/ignore-error/1)

Event Loop是一个程序结构，用于等待和发送消息和事件

**Comment by azl397985856** [comment]
[《一文看懂浏览器事件循环》](https://lucifer.ren/blog/2019/12/11/event-loop/)
