### ISSUE TITLE
【每日一题】- 2019-12-16 - CDN有哪些优化加载静态资源速度的机制？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#83]

**Comment by azl397985856** [comment]
CDN 的核心功能，一个是缓存，一个是回源。

缓存就是说我们把资源复制一份到 CDN 服务器上，回源就是说 CDN 发现自己没有这个资源（一般是缓存的数据过期了），重新向向web 服务器（或者它的上层服务器）重新取这个资源。

- CDN中一方面有很多的缓存策略，从而可以提高加载速度。
- 另一方面CDN有路由算法，可以选择用户访问速度最快的节点进行接入，从而加快RTT(Roud Trip Time)

**Comment by halu886** [comment]
参考[CDN详解](https://segmentfault.com/a/1190000010631404)
梳理了以下两点
1. CDN会挑选最优设备提供服务。可能是Cache最接近用户，或者条件最好的路径。这个过程就叫*均衡负载*
2. *加速分发*，将动态文件结合ESC，静态资源文件结合动态存储OSS实现动静分离

**Comment by wycyftk** [comment]
可以参考阿里云团队的[《CDN之我见》](https://yq.aliyun.com/articles/577708?spm=a2c41.11181499.0.0)。总结如下：
1. 资源调度：CDN会根据用户接入网络的ip寻找距离用户最优路径的服务器。调度的方式主要有DNS调度、http 302调度、使用 HTTP 进行的 DNS 调度（多用于移动端）；
2. 缓存策略和数据检索：CDN服务器使用高效的算法和数据结构，快速的检索资源和更新读取缓存；
3. 网络优化：从OSI七层模型进行优化，达到网络优化的目的。

* L1物理层：硬件设备升级提高速度
* L2数据链路层：寻找更快的网络节点、确保 Lastmile 尽量短
* L3路由层：路径优化，寻找两点间最优路径
* L4传输层：协议TCP优化，保持长连接、TCP快速打开
* L7应用层：静态资源压缩、请求合并

**Comment by azl397985856** [comment]
> 可以参考阿里云团队的[《CDN之我见》](https://yq.aliyun.com/articles/577708?spm=a2c41.11181499.0.0)。总结如下：
> 
> 1. 资源调度：CDN会根据用户接入网络的ip寻找距离用户最优路径的服务器。调度的方式主要有DNS调度、http 302调度、使用 HTTP 进行的 DNS 调度（多用于移动端）；
> 2. 缓存策略和数据检索：CDN服务器使用高效的算法和数据结构，快速的检索资源和更新读取缓存；
> 3. 网络优化：从OSI七层模型分别进行不同的优化，达到网络优化的目的。

3可以详细一点么？这个太宽泛了。
