### ISSUE TITLE
【每日一题】- 2019-12-17 - 诡异的网速

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#84]
用户打开一个网页10次，其中5次比较快，5次比较慢。而你却不能重现。  可能的原因是什么？如何解决？

**Comment by halu886** [comment]
参考[网页加载慢，你知道几种原因?](https://blog.csdn.net/LEoe_/article/details/79475981)
1. 带宽不足
2.硬件配置低
3.CPU或者是内存被占满
4.网页本身中包含了追踪或者是分析用户的工具
5.DNS解析慢

解决思路
1～3可以通过升级用户硬件配置，4将相关工具进行卸载，5通过DNS缓存(TTL)、DNS预读取、拆分域名提升DNS解析速度

**Comment by azl397985856** [comment]
@halu886  这里只是给出了可能性以及对应的解决方案。先不谈你的方案本身。 那么我如何才能知道用户确切是哪一种造成的呢？

**Comment by halu886** [comment]
> @halu886 这里只是给出了可能性以及对应的解决方案。先不谈你的方案本身。 那么我如何才能知道用户确切是哪一种造成的呢？

1.基于teamview远程控制用户机器，进行设备检查/宽带测速 ==》客户端硬件/宽带问题
2.ping测试丢包率和网络时延==》进一步推断网络状况
3.在服务器上基于wireshark进行抓包==》通过每一帧数据包推断出网络传输中存在问题的节点

**Comment by azl397985856** [comment]
> > @halu886 这里只是给出了可能性以及对应的解决方案。先不谈你的方案本身。 那么我如何才能知道用户确切是哪一种造成的呢？
> 
> 1.基于teamview远程控制用户机器，进行设备检查/宽带测速 ==》客户端硬件/宽带问题
> 2.ping测试丢包率和网络时延==》进一步推断网络状况
> 3.在服务器上基于wireshark进行抓包==》通过每一帧数据包推断出网络传输中存在问题的节点

虽然回答的很具体了，但是慢不一定是网速引起的，也可能是别的原因。（PS：难道是我的标题具有欺骗性？）
