### ISSUE TITLE
【每日一题】- 2019-12-31 - 谈一下你对CSS-in-JS的理解，优缺点。

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#90]
CSS-in-JS 在组件层面对 CSS 进行了抽象。在项目中维护一个巨大的样式文件夹实在是一件让人感到头疼的事情，CSS-in-JS 是一种解决方案。 那么有没有别的方案呢？ CSS-in-JS本身有没有什么缺点呢？ 他的优势主要是什么呢？我们是否应该去使用，在什么情况下可以使用？

**Comment by CoderMageFox** [comment]
认领

**Comment by azl397985856** [comment]
> 认领

done

**Comment by yunlovebo** [comment]
这里有一篇文章，标题表明态度 [stop-using-css-in-javascript](https://hackernoon.com/stop-using-css-in-javascript-for-web-development-fa32fb873dcc)
