### ISSUE TITLE
【每日一题】- 2020-01-10 - 飞机上的wifi是怎么连接到外网的？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/fe-interview#93]
有的飞机提供wifi，用户可以用它连接到外网进行上网。 那么飞机在那么高的高空，飞那么快，是如何保证信号的呢？

**Comment by azl397985856** [comment]
简单来说，你需要地面的中转，不然怎么接入地面呢？ 我们可以在航线上设置几个专门用于接入航线上飞机和地面的中转设备。 

这里有一篇[文章](https://onezero.medium.com/what-makes-it-possible-to-browse-the-internet-at-35-000-feet-1afaea83eb5) 讲的很详细。

**Comment by Nicenonecb** [comment]
飞机上有两个平行运行的系统允许你在飞行中保持网络连接。 第一个系统使用地面发射塔的网络，发射信号是由飞机机身下面的接收器接收的。 这本质上是把飞机变成一个飞行热点，允许用户连接。 然后，你的数据会直接从飞机上传到地面。
       当飞机飞行时，它会连接到最近的塔台，在整个飞行过程中从一个塔台切换到另一个塔台。 想象走在一条路上，你有路上所有的咖啡馆和酒吧的Wifi密码；当你走路的时候，你的手机会自动连接到每一个新的信号。这架飞机有点像一个之前所述的巨大的空中版本，它通过下面的塔向乘客传递信号。
      
     1. 通过机舱设置的Wifi天线接收乘客的信号。
     2. 信号发送到飞机上的服务器。
     3. 外部天线将信号发送给卫星，提供地面卫星接入站的覆盖范围。
     4. 如果能直接向地面移动塔发出射程内的信号，如在飞机密集程度较高的地区和覆盖范围较大的地区这种主要枢纽和高密度路线
     5. 另一端在地面，在被引导到它需要去的地方之前，信息通过一个“相遇点”，按照选择路径进行传送。

**Comment by Nicenonecb** [comment]
飞机上有两个平行运行的系统允许你在飞行中保持网络连接。 第一个系统使用地面发射塔的网络，发射信号是由飞机机身下面的接收器接收的。 这本质上是把飞机变成一个飞行热点，允许用户连接。 然后，你的数据会直接从飞机上传到地面。
      当飞机飞行时，它会连接到最近的塔台，在整个飞行过程中从一个塔台切换到另一个塔台。 想象走在一条路上，你有路上所有的咖啡馆和酒吧的Wifi密码；当你走路的时候，你的手机会自动连接到每一个新的信号。这架飞机有点像一个之前所述的巨大的空中版本，它通过下面的塔向乘客传递信号。
 


1. 通过机舱设置的Wifi天线接收乘客的信号。
2. 信号发送到飞机上的服务器。
3. 外部天线将信号发送给卫星，提供地面卫星接入站的覆盖范围。
4. 如果能直接向地面移动塔发出射程内的信号，如在飞机密集程度较高的地区和覆盖范围较大的地区这种主要枢纽和高密度路线
5. 另一端在地面，在被引导到它需要去的地方之前，信息通过一个“相遇点”，按照选择路径进行传送。
